/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Common_Console */

#ifndef _Included_Common_Console
#define _Included_Common_Console
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     Common_Console
	* Method:    gotoXY
	* Signature: (II)V
	*/
	JNIEXPORT void JNICALL Java_Common_Console_gotoXY
		(JNIEnv *, jclass, jint, jint);

	/*
	* Class:     Common_Console
	* Method:    cls
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_Common_Console_cls
		(JNIEnv *, jclass);

	/*
	* Class:     Common_Console
	* Method:    size
	* Signature: (II)V
	*/
	JNIEXPORT void JNICALL Java_Common_Console_size
		(JNIEnv *, jclass, jint, jint);

	/*
	* Class:     Common_Console
	* Method:    whereX
	* Signature: ()I
	*/
	JNIEXPORT jint JNICALL Java_Common_Console_whereX
		(JNIEnv *, jclass);

	/*
	* Class:     Common_Console
	* Method:    whereY
	* Signature: ()I
	*/
	JNIEXPORT jint JNICALL Java_Common_Console_whereY
		(JNIEnv *, jclass);

	/*
	* Class:     Common_Console
	* Method:    setTitle
	* Signature: (Ljava/lang/String;)V
	*/
	JNIEXPORT void JNICALL Java_Common_Console_setTitle
		(JNIEnv *, jclass, jstring);

	/*
	* Class:     Common_Console
	* Method:    backgroundColor
	* Signature: (I)I
	*/
	JNIEXPORT jint JNICALL Java_Common_Console_backgroundColor
		(JNIEnv *, jclass, jint);

	/*
	* Class:     Common_Console
	* Method:    fontColor
	* Signature: (I)I
	*/
	JNIEXPORT jint JNICALL Java_Common_Console_fontColor
		(JNIEnv *, jclass, jint);

	/*
	* Class:     Common_Console
	* Method:    setCursor
	* Signature: (I)V
	*/
	JNIEXPORT void JNICALL Java_Common_Console_setCursor
		(JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
